model:
  name: allenai/OLMo-2-1124-7B
  size: 7b
  layer_mass:
    gate: 0.5
    up: 0.5
    down: 1.0
  layers:
    '23':
      gate: 0.5
      up: 0.5
      down: 1.0
    '24':
      gate: 0.5
      up: 0.5
      down: 1.0
    '25':
      gate: 0.5
      up: 0.5
      down: 1.0
eval_kfac:
  args:
    bs: 96
    bergson-factors: out/collect_kfac/bergson/7b
    layers-json: '{"23": {"gate": 0.5, "up": 0.5, "down": 1.0}, "24": {"gate": 0.5,
      "up": 0.5, "down": 1.0}, "25": {"gate": 0.5, "up": 0.5, "down": 1.0}}'
  use_eigenvalue_corrections: false
  use_weight_coefficients: false
method:
  name: bergson
collect_kfac:
  script: data/collect_kfac_bergson.py
  extra_dep: pyproject.toml
  fsdp: true
  world_size: 8
  args:
    method: shampoo
    device: cuda
    dtype: bfloat16
    corpus: dolmo
    nbytes: 100000000
    seq_len: 512
    target_blocks:
    - '23'
    - '24'
    - '25'
    layers_per_pass: 3
    batch_size: 36
  bf16_batch_size: 40
  sample_labels: true
benchmark:
  args:
    task: gsm8k::olmes
    batch-size: 28
model_method:
  gate_up_mass: 0.5
out_suffix: bergson/7b
out_dir:
  prepare_pile10k: data/pile10k_None.txt
  prepare_pile10k_cache: out/prepare_pile10k_cache
  baseline_cache: out/baseline_cache/7b
  collect_kfac: out/collect_kfac/bergson/7b
  eval_kfac: out/eval_kfac/bergson/7b
  plot_figure2: out/plot_figure2/bergson/7b
  benchmark: out/benchmark/bergson/7b
computed:
  eigenvalue_corrections_flag: ''
  weight_coefficients_flag: ''
  sample_labels_flag: --sample_labels
  fsdp_flag: --fsdp
  world_size_flag: --world_size 8
