model:
  name: allenai/OLMo-2-0425-1B
  size: 1b
  layer_mass:
    gate: 0.4
    up: 0.4
    down: 1.0
  layers:
    '13':
      gate: 0.4
      up: 0.4
      down: 1.0
    '14':
      gate: 0.4
      up: 0.4
      down: 1.0
    '15':
      gate: 0.4
      up: 0.4
      down: 1.0
eval_kfac:
  args:
    bs: 128
    bergson-factors: out/collect_kfac/bergson/1b
    layers-json: '{"13": {"gate": 0.4, "up": 0.4, "down": 1.0}, "14": {"gate": 0.4,
      "up": 0.4, "down": 1.0}, "15": {"gate": 0.4, "up": 0.4, "down": 1.0}}'
  use_eigenvalue_corrections: true
  use_weight_coefficients: false
method:
  name: bergson
collect_kfac:
  script: data/collect_kfac_bergson.py
  extra_dep: bergson/
  fsdp: false
  world_size: 1
  bf16_batch_size: 168
  sample_labels: true
  args:
    device: cuda
    dtype: bfloat16
    corpus: dolmo
    nbytes: 10000
    seq_len: 512
    target_blocks:
    - '13'
    - '14'
    - '15'
    layers_per_pass: 3
    batch_size: 1
benchmark:
  args:
    task: gsm8k::olmes
    batch-size: 28
model_method:
  gate_up_mass: 0.4
out_suffix: bergson/1b
out_dir:
  prepare_pile10k: data/pile10k_None.txt
  prepare_pile10k_cache: out/prepare_pile10k_cache
  baseline_cache: out/baseline_cache/1b
  collect_kfac: out/collect_kfac/bergson/1b
  eval_kfac: out/eval_kfac/bergson/1b
  plot_figure2: out/plot_figure2/bergson/1b
  benchmark: out/benchmark/bergson/1b
computed:
  eigenvalue_corrections_flag: --eigenvalue-corrections
  weight_coefficients_flag: ''
  sample_labels_flag: --sample_labels
  fsdp_flag: ''
  world_size_flag: --world_size 1
